### ISSUE TITLE
parsing larger number of fasta files

### ISSUE THREAD

**Issue by jianshu93** [rchikhi/rust-parallelfastx#3]
Hello Rayan, 

I have more than 1 million fasta files to parse, each is about 3-5 Mb, total is about 3T, I am wondering how I can read those huge number of files in parallel using all cpu cores I have. It seems there are not such tool available right now. Any suggestions?

Thanks,

Jianshu

**Comment by rchikhi** [comment]
Hi Jianshu, GNU parallel seems like your best option.
